import Head from 'next/head'
import Image from 'next/image'
import { useContext } from 'react'
import Header from '../components/Header';
import Main from '../components/Main';
import { EthersContext } from '../context/Connector'

export default function Home() {
  const Eth = useContext(EthersContext);


  
  return (
    <div className='flex flex-col w-full min-h-screen justify-center items-center bg-[#326789]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Main/>

 
      
    </div>
  )
}

